version: "3.9"

name: open_data
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dwh:/docker-entrypoint-initdb.d
      - ./dwh-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dwh-data:
