config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

transform_dmt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: dmt
      port: 8123
      user: user
      password: pass
      secure: False
